### ISSUE TITLE
when the game restarts it automatically opens the welcome screen

### ISSUE THREAD

**Issue by Ox23** [Midorina/TroveFishingBot#2]
when the game restarts it automatically opens the welcome screen and it cant cast the fishing rod, it needs to press F1 after it detects the game,

**Comment by Midorina** [comment]
This does not happen to me. Could you post a screenshot of the welcome screen you're talking about?

**Comment by Midorina** [comment]
I'm closing the issue due to inactivity. Please feel free to re-open if you can add additional information.
